const {Pool}=require('@neondatabase/serverless');const crypto=require('crypto');const {phone,sync}=require('../lib/lucky-draw');function admin(req){const raw=(req.headers.cookie||'').match(/(?:^|; )rg_admin=([^;]*)/);if(!raw)return false;try{const t=decodeURIComponent(raw[1]),[exp,sig]=t.split('.'),key=process.env.ADMIN_AUTH_SECRET||process.env.RESEND_API_KEY||'';if(!key||!exp||Date.now()>Number(exp))return false;const good=crypto.createHmac('sha256',key).update(exp).digest('hex');return sig===good}catch(e){return false}}
module.exports=async(req,res)=>{res.setHeader('Cache-Control','no-store');let pool;try{
const progressOnly=req.method==='GET'&&req.query?.progress==='1';const isAdmin=admin(req);if(req.method!=='GET'&&req.method!=='POST')return res.status(405).end();if(req.method==='GET'&&!isAdmin&&!progressOnly)return res.status(401).json({error:'Please sign in'});
const b=req.body||{};const mobile=phone(b.phone),name=String(b.name||'').trim();if(req.method==='POST'&&(!mobile||name.length<2||name.length>120))return res.status(400).json({error:'Enter your order name and valid Pakistan mobile number'});
pool=new Pool({connectionString:process.env.POSTGRES_URL||process.env.DATABASE_URL||process.env.POSTGRES_URL_NON_POOLING});
if(!isAdmin&&!progressOnly){await pool.query("CREATE TABLE IF NOT EXISTS lucky_lookup_limits(key TEXT PRIMARY KEY,hits INTEGER NOT NULL,window_start TIMESTAMPTZ NOT NULL)");const ip=String(req.headers['x-forwarded-for']||req.socket?.remoteAddress||'unknown').split(',')[0];const key=crypto.createHash('sha256').update(ip).digest('hex');const rate=await pool.query("INSERT INTO lucky_lookup_limits VALUES($1,1,NOW()) ON CONFLICT(key) DO UPDATE SET hits=CASE WHEN lucky_lookup_limits.window_start<NOW()-INTERVAL '10 minutes' THEN 1 ELSE lucky_lookup_limits.hits+1 END,window_start=CASE WHEN lucky_lookup_limits.window_start<NOW()-INTERVAL '10 minutes' THEN NOW() ELSE lucky_lookup_limits.window_start END RETURNING hits",[key]);if(rate.rows[0].hits>20)return res.status(429).json({error:'Please wait 10 minutes before checking again'})}
await sync(pool);
const progressQuery=await pool.query("SELECT COUNT(*)::int AS completed FROM lucky_draw_entries e JOIN orders o ON o.id=e.order_id WHERE o.status='Delivery Complete'");const completed=Number(progressQuery.rows[0]?.completed||0);const progress={completed,target:1000,remaining:Math.max(0,1000-completed),percent:Math.min(100,completed/10)};if(progressOnly)return res.status(200).json({progress});
const offset=Math.max(0,Math.min(1000000,parseInt((req.method==='GET'?req.query?.offset:b.offset)||0)||0));const search=req.method==='GET'?String(req.query?.search||'').trim().slice(0,120):'';const digits=phone(search)||search.replace(/\D/g,'').replace(/^0/,'');const pattern='%'+search.replace(/[\\%_]/g,'\\$&')+'%';const filter=req.method==='GET'?(search?" AND (e.customer_name ILIKE $1 ESCAPE '\\' OR ($2<>'' AND e.phone LIKE '%'||$2||'%') OR ('RG-'||e.serial::text) ILIKE $1 ESCAPE '\\' OR e.order_id::text=$3)":''):" AND e.phone=$1 AND LOWER(TRIM(e.customer_name))=LOWER($2)";const params=req.method==='GET'?(search?[pattern,digits,search.replace(/^#/, '')]:[]):[mobile,name];const base=" FROM lucky_draw_entries e JOIN orders o ON o.id=e.order_id WHERE o.status='Delivery Complete'"+filter;
const count=await pool.query('SELECT COUNT(*)::int AS total,COUNT(DISTINCT e.phone)::int AS customers'+base,params);const rows=await pool.query("SELECT e.serial,e.order_id,e.product_name,e.created_at,e.customer_name"+(req.method==='GET'?',e.phone':'')+base+" ORDER BY e.serial DESC LIMIT 100 OFFSET $"+(params.length+1),[...params,offset]);return res.status(200).json({progress,...count.rows[0],entries:rows.rows,offset,hasMore:offset+rows.rows.length<count.rows[0].total})
}catch(e){console.error('Lucky draw:',e.message);return res.status(500).json({error:'Entries could not be loaded. Please try again.'})}finally{if(pool)await pool.end().catch(()=>{})}};
